# Generated by Django 4.0.3 on 2022-04-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('interes', models.CharField(max_length=10)),
                ('mensaje', models.TextField(default='')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
