# Generated by Django 4.0.3 on 2022-04-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_dueno', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=10)),
                ('colonia', models.CharField(max_length=30)),
                ('estado', models.TextField(default='')),
                ('tipo_credito', models.CharField(max_length=10)),
                ('saldo', models.CharField(blank=True, max_length=20)),
                ('nss', models.IntegerField(blank=True)),
                ('whatsapp', models.IntegerField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
