# Generated by Django 4.0.3 on 2022-04-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='whatsapp',
            field=models.CharField(max_length=10),
        ),
    ]
