# Generated by Django 4.0.3 on 2022-04-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captacion', '0002_alter_propiedad_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propiedad',
            name='nss',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='saldo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
