# Generated by Django 4.0.3 on 2022-04-21 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captacion', '0003_alter_propiedad_nss_alter_propiedad_saldo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Propiedad',
            new_name='Prospecto',
        ),
    ]
