# Generated by Django 4.0.3 on 2022-04-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('colonia', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('descripcion', models.TextField(default='')),
                ('recamaras', models.IntegerField()),
                ('banos', models.FloatField()),
                ('metros_construccion', models.IntegerField()),
                ('metros_terreno', models.IntegerField()),
                ('pisos', models.IntegerField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
