# Generated by Django 4.0.3 on 2022-04-22 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0002_propiedad_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteComprador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
                ('mensaje', models.TextField(default='Hola, me interesa este inmueble que vi y quiero que me contacten. Gracias.')),
                ('propiedad_interes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='propiedades.propiedad')),
            ],
        ),
    ]
